name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # Uncomment when Node.js 14 is EOL'd so the built-in
          # test-runner is available
          # - lts/-2
          - lts/-1
          # Node.js has a segfault in latest v18, have to wait until
          # that's patched to use the latest lts
          # - lts/*

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --global npm
          npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Test
        run: npm test
